//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodCorner
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChefOrder
    {
        public int OrderId { get; set; }
        public int ChefId { get; set; }
        [Display(Name = "Assignment Date")]
        [Required(ErrorMessage = "Assignment Date is needed.")]
        public System.DateTime AssignmentDate { get; set; }
        
        public string Status { get; set; }


        public virtual Employee Employee { get; set; }
        public virtual Order Order { get; set; }
    }

    public enum Status
    {
        Ready,
        InProcess
    }
}
