//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodCorner
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Delivery_Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Delivery_Team()
        {
            this.Orders_DeliveryTeams = new HashSet<Orders_DeliveryTeam>();
            this.TeamMembers = new HashSet<TeamMember>();
        }
    
        public int Id { get; set; }


        [DisplayAttribute(Name = "Delivery Team Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Delivery Team Name s required")]
        public string Name { get; set; }


        [Display(Name = "Create Date")]
        [DataType(DataType.DateTime)]
        [Required(ErrorMessage = "Create Date is needed.")]
        public System.DateTime Create_Date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders_DeliveryTeam> Orders_DeliveryTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TeamMember> TeamMembers { get; set; }
    }
}
