//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodCorner
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class MenuCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuCard()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        public int FoodId { get; set; }

        [DisplayAttribute(Name = "Food Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Food name is required")]
        public string Name { get; set; }

        [DisplayAttribute(Name = "Description")]
        [DataType(DataType.Text)]
        public string Description { get; set; }

        [DisplayAttribute(Name = "Quantity")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Quantity is required")]
        [DataType(DataType.Text)]
        public string QuantityPerUnit { get; set; }

        [DisplayAttribute(Name = "Unit Price")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Unit Price is required")]
        [DataType(DataType.Text)]
        public decimal UnitPrice { get; set; }

        [DisplayName("Picture")]
        public string ImagePath { get; set; }
        public int CategoryId { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }

        public virtual FoodCategory FoodCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
