//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodCorner
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class OrderDetail
    {
        public int OrderId { get; set; }
        public int FoodId { get; set; }

        [DisplayAttribute(Name = "Quantity")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Quantity is required")]
        [DataType(DataType.Text)]
        public int Quantity { get; set; }

        [DisplayAttribute(Name = "Discount Price")]
        [DataType(DataType.Text)]
        public Nullable<decimal> Discount { get; set; }

        [DisplayAttribute(Name = "Price")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Price is required")]
        [DataType(DataType.Text)]
        public decimal Price { get; set; }
    
        public virtual MenuCard MenuCard { get; set; }
        public virtual Order Order { get; set; }
    }
}
