//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodCorner
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Purchased_Item
    {
        public int Id { get; set; }

        [DisplayAttribute(Name = "Product Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Product name required")]
        public string Name { get; set; }

        public int SupplierId { get; set; }
        public int CategoryId { get; set; }

        [DisplayAttribute(Name = "Quantity")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Quantity is required")]
        [DataType(DataType.Text)]
        public string QuantityPerUnit { get; set; }

        [DisplayAttribute(Name = "Unit In Stock")]
        [DataType(DataType.Text)]
        public Nullable<int> UnitsInStock { get; set; }

        [DisplayAttribute(Name = "Unit Price")]
        [DataType(DataType.Text)]
        public Nullable<decimal> UnitPrice { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
