//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFoodCorner
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Purchased_Items = new HashSet<Purchased_Item>();
        }
    
        public int SupplierId { get; set; }
        [DisplayAttribute(Name = "Company Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Company name required")]
        public string CompanyName { get; set; }
        [DisplayAttribute(Name = "Contact Name")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Contact name required")]
        public string ContactName { get; set; }
        public string Address { get; set; }
        [Required(ErrorMessage = "Phone Number is needed.")]
        [Display(Name = "Contact No")]
        [DataType(DataType.PhoneNumber)]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Invalid Phone number")]
        public string PhoneNo { get; set; }
        [Required(AllowEmptyStrings = false, ErrorMessage = "City name is required")]
        [DataType(DataType.Text)]
        public string City { get; set; }
        [DisplayAttribute(Name = "Country")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Country name is required")]
        [DataType(DataType.Text)]
        public string Country { get; set; }
        [DisplayAttribute(Name = "Area")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Area is required")]
        [DataType(DataType.Text)]
        public string Area { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchased_Item> Purchased_Items { get; set; }
    }
}
